
#include "stm32f0xx_hal.h"
#include "main.h"
#include <string.h>

void SystemClockConfig(void);
void GPIO_Init(void);
void TIMER6_Init(void);

void Error_handler(void);

TIM_HandleTypeDef htimer6;


int main(void)
{
	HAL_Init();
	SystemClockConfig();

	GPIO_Init();

	TIMER6_Init();


	/*
	 * START TİMER
	 *  */
	HAL_TIM_Base_Start_IT(&htimer6);


	return 0;
}

void SystemClockConfig(void)
{

}


void TIMER6_Init(void)
{
	htimer6.Instance = TIM6;
	htimer6.Init.Prescaler = 7;
	htimer6.Init.Period = 60000 - 1;

	if(HAL_TIM_Base_Init(&htimer6) != HAL_OK)
	{
		Error_handler();
	}

}

/*
 * An IRQ can be generated by different events of the same peripheral,
 * in order to write specific functions for that particular event, a callback function is being used inside which the user code is defined.
 * */
void HAL_TIM_PeriodElapsedCallback(TIM_HandleTypeDef *htim)
{
	HAL_GPIO_TogglePin(GPIOA, GPIO_PIN_5);
}


void GPIO_Init(void)
{
	__HAL_RCC_GPIOA_CLK_ENABLE();

	GPIO_InitTypeDef ledgpio;
	ledgpio.Pin = GPIO_PIN_5;
	ledgpio.Mode = GPIO_MODE_OUTPUT_PP;
	ledgpio.Pull = GPIO_NOPULL;
	HAL_GPIO_Init(GPIOA, &ledgpio);
}


void Error_handler(void)
{
	while(1);
}


